### ISSUE TITLE
Support vertical slides

### ISSUE THREAD

**Issue by sobkowiak** [cmoulliard/hyla#63]
Reveal.js provides support for vertical slides generated from subsections of the 1st level slides. Would it be possible to support this in hyla too?

**Comment by cmoulliard** [comment]
Hi Krzysztof,

This option is supported. Here is the trick to use nested slides :  

http://cmoulliard.github.io/learnasciidoctor/#/_nested_slides

````
== &nbsp; // Trick to avoid to display the slide parent section

=== Nested slides // First Nested slide

.Unordered list
* Item 1
* Item 2

=== Nested slides // Second Nested slide

````
