### ISSUE TITLE
Vertically fill screen 100%? 

### ISSUE THREAD

**Issue by cmoulliard** [cmoulliard/hyla#85]
Issue description : https://github.com/hakimel/reveal.js/issues/180

Trick added to gpe.css

```
/********************************
 * Fill screen to 100%
 ********************************/
.reveal .slides {
  top: 370px;
}
```

**Comment by cmoulliard** [comment]
Merge gpe.css with file send by Randy Thomas (26/Feb)

**Comment by randythomas** [comment]
Hi Charles.  I assume the fix is more than just the change go gpe.css?  I added that change yesterday and did not see any change to the header.  How does the fix get applied?

**Comment by cmoulliard** [comment]
The trick is working for me. Here is the screenshot taken before 
![screenshot 2015-03-01 10 39 45](https://cloud.githubusercontent.com/assets/463790/6430187/a3121d00-bfff-11e4-87f2-a6dedf03422a.png) and after 
![screenshot 2015-03-01 10 38 39](https://cloud.githubusercontent.com/assets/463790/6430191/a92d5fe2-bfff-11e4-92b0-a2f50e378bf4.png)

Size of the browser : 1280x600

Modification : 

```
/******************************************
 * Fill screen to 100% & align text on left
 * Feb 26, CHM : Add top: 370px to fill the screen to 100%
 ******************************************/
.reveal .slides {
    text-align: left;
    top: 370px;
}
```
