### ISSUE TITLE
Refactor notescript section of cover, index, labinstruction & file created

### ISSUE THREAD

**Issue by cmoulliard** [cmoulliard/hyla#89]
The existing __notescript__ section is not longer up to date and should be based on this definition : 

```
ifdef::showscript[]
[.notes]
****
//tag::snippet[]

//end::snippet[]
****
endif::[]
```

Why : 

* [•notes] asciidoctor role (= css class) must be added in order to generate <aside class="notes"/> for revealjs notes instructors
* **** is mandatory otherwise the <asdide/> (= sidebar) is not generated by asciidoctor

**Comment by randythomas** [comment]
Showscript is documented in the guide in section 5: https://github.com/redhat-gpe/OPEN_common/blob/master/course_developer_guide/OPEN_Course_Developer_Guide.adoc#54-audio-script-requirements

However "//tag::snippet[]" is not included.  What does this piece do?
